credentials:
  usernames:
    jo-cera:
      email: joycemacharia02@gmail.com
      logged_in: False # Will be managed automatically
      name: Joyce Macharia
      password: '123456' # Will be hashed automatically
cookie:
  expiry_days: 0
  key: cookie_signature_key # Must be string
  name: cookie_name
preauthorized:
  emails:
  - joyce.macharia@azubiafrica.org
users: